### ISSUE TITLE
ws-federation  configuraiton

### ISSUE THREAD

**Issue by divyang4481** [LinqBeast/IdentityServer3.Contrib.Configuration#1]
is it possible to use or  extend this configuration to config  identity server as  RP-STS  with ADFS and relay party

**Comment by bobbydowling** [comment]
A little late now, I suppose.  I assume you sorted it out, at this point.

**Comment by bobbydowling** [comment]
A little late now, I suppose. I assume you sorted it out, at this point.

Marking this closed.
